# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7e4934278d2cf1a6008356b0695c60d37c3f4507eb91640edd1505887ed4f82c2250ba87c0c48c18a0df42a0f267296fd1bf6348fe0d3ed12f7e13364e9847

test:
  secret_key_base: 62dba91c4b55a0ac754b8fbea512475e50b528d906573c717b57269d175223b1793502844397c66a4b0e91f95f4ba18d41853e69db6c6ea1d7f3e5419e013f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
